/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GrammarTip = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
});
export const Phrase = IDL.Record({
  'category' : IDL.Text,
  'phrase' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'studentName' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllGrammarTipsByCategory' : IDL.Func(
      [],
      [IDL.Vec(GrammarTip)],
      ['query'],
    ),
  'getAllLessonsByRating' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllPhrasesByCategory' : IDL.Func([], [IDL.Vec(Phrase)], ['query']),
  'getGrammarTips' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(GrammarTip)],
      ['query'],
    ),
  'getLessons' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Lesson)], ['query']),
  'getPhrases' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Phrase)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GrammarTip = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const Phrase = IDL.Record({ 'category' : IDL.Text, 'phrase' : IDL.Text });
  const Testimonial = IDL.Record({
    'studentName' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllGrammarTipsByCategory' : IDL.Func(
        [],
        [IDL.Vec(GrammarTip)],
        ['query'],
      ),
    'getAllLessonsByRating' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllPhrasesByCategory' : IDL.Func([], [IDL.Vec(Phrase)], ['query']),
    'getGrammarTips' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(GrammarTip)],
        ['query'],
      ),
    'getLessons' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Lesson)], ['query']),
    'getPhrases' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Phrase)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };